steps:
  - id: "maven-build"
    name: "gcr.io/cloud-builders/mvn"
    args: ["clean", "package", "-DskipTests"]
    timeout: 200s

  - id: "docker-build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "europe-southwest1-docker.pkg.dev/wrk25communication/coms-repository/coms-image", "."]
    timeout: 200s

  - id: "push-docker-image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-southwest1-docker.pkg.dev/wrk25communication/coms-repository/coms-image"]
    timeout: 200s