name: GCP Deployment Pipeline

on:
  workflow_run:
    workflows: ["Tests and Coverage Validation"]
    types:
      - completed
    branches:
      - main

jobs:
  gcp_deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código (necesario para obtener el SHA del commit)
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Autenticación en GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.COMS_KEY }}

      # Paso 3: Configurar Docker
      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker europe-southwest1-docker.pkg.dev

      # Paso 4: Construir imagen con tag único (SHA del commit)
      - name: Build Docker image
        run: |
          docker build \
            -t europe-southwest1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/coms-repository/coms-image:${{ github.sha }} \
            -t europe-southwest1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/coms-repository/coms-image:latest \
            .

      # Paso 5: Subir ambas versiones de la imagen
      - name: Push Docker images
        run: |
          docker push europe-southwest1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/coms-repository/coms-image:${{ github.sha }}
          docker push europe-southwest1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/coms-repository/coms-image:latest

      # Paso 6: Desplegar en Cloud Run con el tag único
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ secrets.COMS_RUN_SERVICE }}
          image: europe-southwest1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/coms-repository/coms-image:${{ github.sha }}  # Tag único aquí
          region: ${{ secrets.GCP_REGION }}
          credentials: ${{ secrets.COMS_KEY }}
          allow_unauthenticated: true
          flags: "--no-traffic"  # Fuerza nueva revisión